[2024-03-09T00:53:30.989+0000] {processor.py:161} INFO - Started process (PID=7002) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:53:30.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:53:30.991+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:53:30.991+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:53:31.005+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:53:31.002+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T00:53:31.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:53:31.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.032 seconds
[2024-03-09T00:54:01.126+0000] {processor.py:161} INFO - Started process (PID=7009) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:54:01.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:54:01.127+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:54:01.127+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:54:01.138+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:54:01.136+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T00:54:01.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:54:01.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T00:54:20.224+0000] {processor.py:161} INFO - Started process (PID=7017) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:54:20.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:54:20.226+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:54:20.226+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:54:20.238+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:54:20.236+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from ..scripts.scrape_data_from_scrapethissite import scrape_countries_data
ImportError: attempted relative import with no known parent package
[2024-03-09T00:54:20.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:54:20.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.032 seconds
[2024-03-09T00:54:21.246+0000] {processor.py:161} INFO - Started process (PID=7018) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:54:21.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:54:21.247+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:54:21.247+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:54:21.261+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:54:21.259+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from ..scripts.scrape_data_from_scrapethissite import scrape_countries_data
ImportError: attempted relative import with no known parent package
[2024-03-09T00:54:21.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:54:21.278+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.035 seconds
[2024-03-09T00:54:51.419+0000] {processor.py:161} INFO - Started process (PID=7025) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:54:51.420+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:54:51.420+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:54:51.420+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:54:51.428+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:54:51.426+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from ..scripts.scrape_data_from_scrapethissite import scrape_countries_data
ImportError: attempted relative import with no known parent package
[2024-03-09T00:54:51.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:54:51.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.024 seconds
[2024-03-09T00:55:16.540+0000] {processor.py:161} INFO - Started process (PID=7032) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:55:16.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:55:16.542+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:55:16.542+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:55:16.554+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:55:16.552+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from ..scripts.scrape_data_from_scrapethissite import scrape_countries_data
ImportError: attempted relative import with no known parent package
[2024-03-09T00:55:16.555+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:55:16.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T00:55:46.689+0000] {processor.py:161} INFO - Started process (PID=7039) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:55:46.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:55:46.691+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:55:46.690+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:55:46.699+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:55:46.697+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from ..scripts.scrape_data_from_scrapethissite import scrape_countries_data
ImportError: attempted relative import with no known parent package
[2024-03-09T00:55:46.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:55:46.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T00:56:16.840+0000] {processor.py:161} INFO - Started process (PID=7046) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:56:16.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:56:16.842+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:56:16.842+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:56:16.853+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:56:16.850+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from ..scripts.scrape_data_from_scrapethissite import scrape_countries_data
ImportError: attempted relative import with no known parent package
[2024-03-09T00:56:16.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:56:16.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.034 seconds
[2024-03-09T00:56:46.981+0000] {processor.py:161} INFO - Started process (PID=7053) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:56:46.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:56:46.982+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:56:46.982+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:56:46.989+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:56:46.987+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from ..scripts.scrape_data_from_scrapethissite import scrape_countries_data
ImportError: attempted relative import with no known parent package
[2024-03-09T00:56:46.990+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:56:47.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.025 seconds
[2024-03-09T00:57:17.122+0000] {processor.py:161} INFO - Started process (PID=7060) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:57:17.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:57:17.124+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:57:17.123+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:57:17.132+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:57:17.130+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from ..scripts.scrape_data_from_scrapethissite import scrape_countries_data
ImportError: attempted relative import with no known parent package
[2024-03-09T00:57:17.133+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:57:17.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.028 seconds
[2024-03-09T00:57:33.207+0000] {processor.py:161} INFO - Started process (PID=7061) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:57:33.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:57:33.209+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:57:33.209+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:57:33.225+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:57:33.223+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T00:57:33.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:57:33.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.038 seconds
[2024-03-09T00:58:03.370+0000] {processor.py:161} INFO - Started process (PID=7068) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:03.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:58:03.372+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:03.371+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:03.382+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:03.380+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T00:58:03.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:03.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.031 seconds
[2024-03-09T00:58:30.511+0000] {processor.py:161} INFO - Started process (PID=7074) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:30.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:58:30.513+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:30.512+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:30.530+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:30.527+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25, in <module>
    python_callable=scrape_countries_data,
NameError: name 'scrape_countries_data' is not defined
[2024-03-09T00:58:30.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:30.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.035 seconds
[2024-03-09T00:58:37.577+0000] {processor.py:161} INFO - Started process (PID=7075) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:37.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:58:37.579+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:37.578+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:37.594+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:37.592+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 22, in <module>
    scrape_country_task = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2024-03-09T00:58:37.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:37.610+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.036 seconds
[2024-03-09T00:58:54.667+0000] {processor.py:161} INFO - Started process (PID=7081) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:54.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:58:54.668+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:54.668+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:54.684+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:54.682+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25, in <module>
    python_callable=scrape_countries_data,
NameError: name 'scrape_countries_data' is not defined
[2024-03-09T00:58:54.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:54.698+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.033 seconds
[2024-03-09T00:58:58.712+0000] {processor.py:161} INFO - Started process (PID=7082) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:58.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:58:58.713+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:58.713+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:58.728+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:58.726+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T00:58:58.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:58.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.033 seconds
[2024-03-09T00:58:59.739+0000] {processor.py:161} INFO - Started process (PID=7083) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:59.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:58:59.741+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:59.741+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:59.756+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:58:59.754+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T00:58:59.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:58:59.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.033 seconds
[2024-03-09T00:59:29.901+0000] {processor.py:161} INFO - Started process (PID=7090) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:59:29.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T00:59:29.902+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:59:29.902+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:59:29.911+0000] {logging_mixin.py:188} INFO - [2024-03-09T00:59:29.909+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T00:59:29.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T00:59:29.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.028 seconds
[2024-03-09T01:00:00.040+0000] {processor.py:161} INFO - Started process (PID=7097) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:00:00.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:00:00.042+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:00:00.041+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:00:00.051+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:00:00.049+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:00:00.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:00:00.069+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.031 seconds
[2024-03-09T01:00:30.176+0000] {processor.py:161} INFO - Started process (PID=7105) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:00:30.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:00:30.177+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:00:30.177+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:00:30.188+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:00:30.186+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:00:30.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:00:30.207+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.033 seconds
[2024-03-09T01:00:33.213+0000] {processor.py:161} INFO - Started process (PID=7106) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:00:33.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:00:33.215+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:00:33.214+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:00:33.233+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:00:33.230+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:00:33.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:00:33.251+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.041 seconds
[2024-03-09T01:01:03.367+0000] {processor.py:161} INFO - Started process (PID=7113) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:01:03.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:01:03.369+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:01:03.368+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:01:03.378+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:01:03.377+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:01:03.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:01:03.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.027 seconds
[2024-03-09T01:01:33.509+0000] {processor.py:161} INFO - Started process (PID=7120) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:01:33.510+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:01:33.510+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:01:33.510+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:01:33.520+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:01:33.518+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:01:33.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:01:33.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.028 seconds
[2024-03-09T01:02:01.645+0000] {processor.py:161} INFO - Started process (PID=7127) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:02:01.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:02:01.646+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:02:01.646+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:02:01.661+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:02:01.658+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:02:01.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:02:01.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.034 seconds
[2024-03-09T01:02:31.788+0000] {processor.py:161} INFO - Started process (PID=7134) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:02:31.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:02:31.790+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:02:31.790+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:02:31.799+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:02:31.798+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:02:31.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:02:31.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.028 seconds
[2024-03-09T01:03:01.923+0000] {processor.py:161} INFO - Started process (PID=7141) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:03:01.924+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:03:01.925+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:03:01.925+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:03:01.934+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:03:01.933+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:03:01.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:03:01.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:03:32.138+0000] {processor.py:161} INFO - Started process (PID=7148) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:03:32.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:03:32.152+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:03:32.152+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:03:32.168+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:03:32.165+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:03:32.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:03:32.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.059 seconds
[2024-03-09T01:04:02.286+0000] {processor.py:161} INFO - Started process (PID=7155) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:04:02.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:04:02.288+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:04:02.287+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:04:02.299+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:04:02.297+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:04:02.300+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:04:02.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.035 seconds
[2024-03-09T01:04:32.465+0000] {processor.py:161} INFO - Started process (PID=7162) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:04:32.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:04:32.466+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:04:32.466+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:04:32.476+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:04:32.474+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:04:32.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:04:32.490+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.027 seconds
[2024-03-09T01:05:02.614+0000] {processor.py:161} INFO - Started process (PID=7169) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:05:02.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:05:02.616+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:05:02.616+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:05:02.626+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:05:02.624+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:05:02.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:05:02.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T01:05:32.755+0000] {processor.py:161} INFO - Started process (PID=7176) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:05:32.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:05:32.756+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:05:32.756+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:05:32.767+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:05:32.765+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:05:32.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:05:32.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.032 seconds
[2024-03-09T01:06:02.900+0000] {processor.py:161} INFO - Started process (PID=7183) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:06:02.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:06:02.901+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:06:02.901+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:06:02.911+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:06:02.909+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:06:02.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:06:02.927+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:06:33.038+0000] {processor.py:161} INFO - Started process (PID=7190) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:06:33.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:06:33.040+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:06:33.039+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:06:33.049+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:06:33.047+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:06:33.050+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:06:33.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.027 seconds
[2024-03-09T01:07:03.178+0000] {processor.py:161} INFO - Started process (PID=7197) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:07:03.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:07:03.179+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:07:03.179+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:07:03.189+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:07:03.187+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:07:03.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:07:03.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:07:33.321+0000] {processor.py:161} INFO - Started process (PID=7204) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:07:33.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:07:33.323+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:07:33.323+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:07:33.334+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:07:33.332+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:07:33.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:07:33.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.032 seconds
[2024-03-09T01:08:03.462+0000] {processor.py:161} INFO - Started process (PID=7211) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:08:03.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:08:03.463+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:08:03.463+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:08:03.475+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:08:03.471+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:08:03.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:08:03.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.031 seconds
[2024-03-09T01:08:33.621+0000] {processor.py:161} INFO - Started process (PID=7218) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:08:33.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:08:33.623+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:08:33.623+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:08:33.632+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:08:33.631+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:08:33.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:08:33.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.028 seconds
[2024-03-09T01:09:03.765+0000] {processor.py:161} INFO - Started process (PID=7225) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:09:03.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:09:03.766+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:09:03.766+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:09:03.776+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:09:03.774+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:09:03.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:09:03.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.028 seconds
[2024-03-09T01:09:22.865+0000] {processor.py:161} INFO - Started process (PID=7232) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:09:22.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:09:22.866+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:09:22.866+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:09:22.880+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:09:22.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 4, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:09:22.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:09:22.896+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.033 seconds
[2024-03-09T01:09:31.927+0000] {processor.py:161} INFO - Started process (PID=7233) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:09:31.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:09:31.929+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:09:31.929+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:09:31.945+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:09:31.943+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:09:31.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:09:31.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.037 seconds
[2024-03-09T01:10:02.078+0000] {processor.py:161} INFO - Started process (PID=7240) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:10:02.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:10:02.080+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:10:02.080+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:10:02.090+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:10:02.088+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:10:02.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:10:02.105+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:11:07.213+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:11:07.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:11:07.215+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:11:07.215+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:11:07.228+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:11:07.225+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:11:07.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:11:07.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.034 seconds
[2024-03-09T01:11:37.378+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:11:37.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:11:37.380+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:11:37.380+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:11:37.391+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:11:37.389+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:11:37.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:11:37.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.032 seconds
[2024-03-09T01:12:07.517+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:12:07.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:12:07.518+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:12:07.518+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:12:07.529+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:12:07.527+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:12:07.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:12:07.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.031 seconds
[2024-03-09T01:12:31.639+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:12:31.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:12:31.642+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:12:31.642+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:12:31.655+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:12:31.654+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:12:31.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:12:31.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.037 seconds
[2024-03-09T01:13:01.778+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:13:01.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:13:01.781+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:13:01.781+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:13:01.790+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:13:01.789+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:13:01.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:13:01.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T01:13:31.939+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:13:31.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:13:31.941+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:13:31.941+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:13:31.953+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:13:31.951+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:13:31.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:13:31.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.033 seconds
[2024-03-09T01:14:02.079+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:14:02.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:14:02.081+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:14:02.081+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:14:02.091+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:14:02.089+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:14:02.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:14:02.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T01:14:32.229+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:14:32.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:14:32.231+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:14:32.231+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:14:32.241+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:14:32.239+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:14:32.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:14:32.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:15:02.375+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:15:02.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:15:02.377+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:15:02.376+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:15:02.387+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:15:02.385+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:15:02.388+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:15:02.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T01:15:32.522+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:15:32.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:15:32.524+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:15:32.524+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:15:32.534+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:15:32.532+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:15:32.535+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:15:32.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.028 seconds
[2024-03-09T01:16:02.674+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:16:02.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:16:02.677+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:16:02.677+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:16:02.689+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:16:02.687+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:16:02.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:16:02.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.036 seconds
[2024-03-09T01:16:32.837+0000] {processor.py:161} INFO - Started process (PID=117) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:16:32.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:16:32.839+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:16:32.839+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:16:32.849+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:16:32.847+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:16:32.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:16:32.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:17:02.978+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:17:02.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:17:02.981+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:17:02.980+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:17:02.991+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:17:02.988+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:17:02.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:17:03.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:17:33.129+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:17:33.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:17:33.132+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:17:33.132+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:17:33.142+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:17:33.140+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:17:33.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:17:33.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T01:18:03.280+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:18:03.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:18:03.282+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:18:03.282+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:18:03.293+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:18:03.291+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:18:03.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:18:03.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.031 seconds
[2024-03-09T01:18:33.426+0000] {processor.py:161} INFO - Started process (PID=145) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:18:33.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:18:33.428+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:18:33.428+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:18:33.438+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:18:33.436+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:18:33.439+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:18:33.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.031 seconds
[2024-03-09T01:19:03.572+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:19:03.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:19:03.574+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:19:03.574+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:19:03.585+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:19:03.583+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:19:03.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:19:03.601+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T01:19:33.720+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:19:33.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:19:33.722+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:19:33.722+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:19:33.733+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:19:33.731+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:19:33.733+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:19:33.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T01:20:03.859+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:20:03.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:20:03.861+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:20:03.860+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:20:03.869+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:20:03.868+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:20:03.870+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:20:03.886+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T01:20:34.003+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:20:34.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:20:34.005+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:20:34.005+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:20:34.016+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:20:34.014+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:20:34.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:20:34.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.031 seconds
[2024-03-09T01:21:04.140+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:21:04.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:21:04.142+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:21:04.142+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:21:04.151+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:21:04.149+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:21:04.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:21:04.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:21:34.297+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:21:34.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:21:34.299+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:21:34.299+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:21:34.310+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:21:34.307+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:21:34.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:21:34.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T01:22:04.437+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:22:04.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:22:04.439+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:22:04.439+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:22:04.449+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:22:04.447+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:22:04.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:22:04.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:22:34.578+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:22:34.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:22:34.580+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:22:34.580+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:22:34.589+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:22:34.588+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:22:34.590+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:22:34.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.027 seconds
[2024-03-09T01:23:04.711+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:23:04.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:23:04.714+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:23:04.713+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:23:04.723+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:23:04.721+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:23:04.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:23:04.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.028 seconds
[2024-03-09T01:23:34.851+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:23:34.852+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:23:34.853+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:23:34.853+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:23:34.862+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:23:34.861+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:23:34.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:23:34.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.027 seconds
[2024-03-09T01:24:04.987+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:24:04.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:24:04.988+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:24:04.988+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:24:04.998+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:24:04.996+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:24:04.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:24:05.014+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:24:35.128+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:24:35.129+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:24:35.130+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:24:35.130+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:24:35.141+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:24:35.139+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:24:35.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:24:35.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.032 seconds
[2024-03-09T01:25:05.265+0000] {processor.py:161} INFO - Started process (PID=238) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:25:05.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:25:05.267+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:25:05.267+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:25:05.276+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:25:05.274+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:25:05.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:25:05.291+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.028 seconds
[2024-03-09T01:25:35.408+0000] {processor.py:161} INFO - Started process (PID=245) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:25:35.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:25:35.410+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:25:35.410+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:25:35.420+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:25:35.418+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:25:35.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:25:35.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T01:26:05.550+0000] {processor.py:161} INFO - Started process (PID=252) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:26:05.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:26:05.552+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:26:05.552+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:26:05.561+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:26:05.559+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:26:05.561+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:26:05.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.026 seconds
[2024-03-09T01:26:35.711+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:26:35.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:26:35.713+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:26:35.713+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:26:35.722+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:26:35.721+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 12, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:26:35.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:26:35.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.028 seconds
[2024-03-09T01:26:56.826+0000] {processor.py:161} INFO - Started process (PID=266) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:26:56.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:26:56.828+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:26:56.828+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:26:56.845+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:26:56.842+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 5, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:26:56.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:26:56.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.041 seconds
[2024-03-09T01:27:26.966+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:27:26.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:27:26.968+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:27:26.967+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:27:26.976+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:27:26.975+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 5, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:27:26.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:27:26.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.026 seconds
[2024-03-09T01:27:53.091+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:27:53.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:27:53.094+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:27:53.094+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:27:53.101+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:27:53.101+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:27:53.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:27:53.116+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.026 seconds
[2024-03-09T01:28:23.233+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:28:23.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:28:23.236+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:28:23.236+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:28:23.244+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:28:23.243+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:28:23.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:28:23.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.027 seconds
[2024-03-09T01:28:53.373+0000] {processor.py:161} INFO - Started process (PID=288) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:28:53.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:28:53.375+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:28:53.375+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:28:53.383+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:28:53.383+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:28:53.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:28:53.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.027 seconds
[2024-03-09T01:29:23.510+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:29:23.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:29:23.513+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:29:23.513+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:29:23.520+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:29:23.520+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:29:23.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:29:23.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.025 seconds
[2024-03-09T01:29:53.641+0000] {processor.py:161} INFO - Started process (PID=302) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:29:53.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:29:53.643+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:29:53.643+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:29:53.651+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:29:53.650+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:29:53.651+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:29:53.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.027 seconds
[2024-03-09T01:30:23.771+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:30:23.772+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:30:23.773+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:30:23.773+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:30:23.780+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:30:23.779+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:30:23.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:30:23.793+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.024 seconds
[2024-03-09T01:30:53.906+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:30:53.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:30:53.908+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:30:53.908+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:30:53.915+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:30:53.915+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:30:53.916+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:30:53.931+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.026 seconds
[2024-03-09T01:31:24.068+0000] {processor.py:161} INFO - Started process (PID=323) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:31:24.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:31:24.070+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:31:24.070+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:31:24.078+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:31:24.077+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:31:24.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:31:24.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.026 seconds
[2024-03-09T01:31:54.210+0000] {processor.py:161} INFO - Started process (PID=330) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:31:54.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:31:54.212+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:31:54.211+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:31:54.220+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:31:54.220+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:31:54.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:31:54.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.027 seconds
[2024-03-09T01:32:24.352+0000] {processor.py:161} INFO - Started process (PID=337) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:32:24.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:32:24.355+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:32:24.354+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:32:24.363+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:32:24.362+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:32:24.363+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:32:24.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:32:54.487+0000] {processor.py:161} INFO - Started process (PID=344) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:32:54.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:32:54.489+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:32:54.489+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:32:54.499+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:32:54.498+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:32:54.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:32:54.521+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.036 seconds
[2024-03-09T01:33:24.622+0000] {processor.py:161} INFO - Started process (PID=351) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:33:24.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:33:24.623+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:33:24.623+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:33:24.631+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:33:24.630+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:33:24.631+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:33:24.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.025 seconds
[2024-03-09T01:33:54.769+0000] {processor.py:161} INFO - Started process (PID=364) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:33:54.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:33:54.771+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:33:54.771+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:33:54.779+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:33:54.778+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:33:54.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:33:54.793+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.026 seconds
[2024-03-09T01:34:24.900+0000] {processor.py:161} INFO - Started process (PID=371) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:34:24.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:34:24.902+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:34:24.901+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:34:24.909+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:34:24.909+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:34:24.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:34:24.924+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.027 seconds
[2024-03-09T01:34:55.040+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:34:55.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:34:55.042+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:34:55.042+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:34:55.052+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:34:55.051+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 25
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:34:55.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:34:55.069+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.031 seconds
[2024-03-09T01:35:12.129+0000] {processor.py:161} INFO - Started process (PID=380) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:35:12.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:35:12.132+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:35:12.132+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:35:12.141+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:35:12.140+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 28
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:35:12.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:35:12.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.028 seconds
[2024-03-09T01:35:32.243+0000] {processor.py:161} INFO - Started process (PID=387) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:35:32.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:35:32.245+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:35:32.245+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:35:32.253+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:35:32.253+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 29
    python_callable=sc.,
                       ^
SyntaxError: invalid syntax
[2024-03-09T01:35:32.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:35:32.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:35:42.301+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:35:42.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:35:42.303+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:35:42.303+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:35:42.316+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:35:42.314+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 9, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:35:42.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:35:42.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.032 seconds
[2024-03-09T01:36:12.480+0000] {processor.py:161} INFO - Started process (PID=395) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:36:12.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:36:12.482+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:36:12.482+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:36:12.491+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:36:12.489+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 9, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:36:12.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:36:12.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.029 seconds
[2024-03-09T01:36:42.612+0000] {processor.py:161} INFO - Started process (PID=402) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:36:42.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:36:42.614+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:36:42.613+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:36:42.623+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:36:42.621+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 9, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:36:42.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:36:42.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.030 seconds
[2024-03-09T01:36:53.671+0000] {processor.py:161} INFO - Started process (PID=403) to work on /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:36:53.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scrape_this_site.py for tasks to queue
[2024-03-09T01:36:53.674+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:36:53.673+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:36:53.689+0000] {logging_mixin.py:188} INFO - [2024-03-09T01:36:53.686+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scrape_this_site.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scrape_this_site.py", line 9, in <module>
    from scripts.scrape_data_from_scrapethissite import scrape_countries_data
ModuleNotFoundError: No module named 'scripts.scrape_data_from_scrapethissite'
[2024-03-09T01:36:53.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scrape_this_site.py
[2024-03-09T01:36:53.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scrape_this_site.py took 0.035 seconds
